### ISSUE TITLE
SSL Protocol Error

### ISSUE THREAD

**Issue by Play-Tiger** [searx/searx-docker#116]
I just finished setting up searxng, but when I'm trying to enter the website it's just telling me this error "ERR_SSL_PROTOCOL_ERROR".
I've set up .env like this and I created an encryption key.
![image](https://user-images.githubusercontent.com/76755673/177201347-1c074a91-9fb7-4d6e-8101-2d6f19801ad3.png)
If you now look at the docker-compose.yaml file you can see that under environment the hostname and letsencrypt mail are still standard parameters.
![image](https://user-images.githubusercontent.com/76755673/177201571-d59a84fd-1b54-4adc-bfef-504ccb7ec169.png)

Does anybody know how to fix this?

**Comment by unixfox** [comment]
This is not the searxng repository.

**Comment by Play-Tiger** [comment]
oh yes, sorry
