### ISSUE TITLE
Settings from settings.yml don't affect searx

### ISSUE THREAD

**Issue by hivefi** [searx/searx-docker#121]
Hey, I followed the steps to install searx-docker and it runs fine. But I have a problem: when I edit searx/settings.yml, nothing changes in searx. I tried restarting the service and the server, but it still shows the default settings. Any ideas?

**Comment by unixfox** [comment]
This project is not maintained anymore, please switch to https://github.com/searxng/searxng-docker

**Comment by hivefi** [comment]
Ok, thanks.
