### ISSUE TITLE
port 8080 is already in use by a different service

### ISSUE THREAD

**Issue by itsjustnickdev** [searx/searx-docker#123]
Hello,

The port 8080 is already in use on my server and can't change that port.
I changed the port in the docker compose file, but it still tries to run it on 8080/tcp and on when checking the site on the browser it displays nothing only a black background.

![afbeelding](https://github.com/user-attachments/assets/f1c9e4c0-659c-4648-a591-7e805eaf3a87)

**Comment by unixfox** [comment]
wrong repo
