### ISSUE TITLE
Rate limit exceeded when hiding instance behind CloudFlare

### ISSUE THREAD

**Issue by dgraziotin** [searx/searx-docker#13]
When my searx instance is hidden behind CloudFlare, search does not work. I always receive "Rate limit exceeded" no matter what. The moment I disable CloudFlare, it works immediately.

I suspect that Filtron somehow does not correctly receive the IP from the request. Is there any settings I need to perform like one would need to do with nginx (example: https://pauledenburg.com/set-nginx-proxy-docker-containers/)?

**Comment by dalf** [comment]
I think you should add ```realip cloudflare```  after ```root /srv``` in Caddyfile (not tested)

See : https://caddyserver.com/v1/docs/http.realip

**Comment by dgraziotin** [comment]
Thanks for this. While the settings seems to apply correctly, it seems that it does not fix the issue.

**Comment by dgraziotin** [comment]
After a bit of debugging Filtron, I found out that the issue was with Brotli. Removing the block about Brotli in [rules.json](https://github.com/searx/searx-docker/blob/master/rules.json#L76) solves the issue for me.
