### ISSUE TITLE
Infinite scroll plugin incompatible with filtron rule

### ISSUE THREAD

**Issue by zhengqunkoo** [searx/searx-docker#16]
When hosing on localhost, this part of `rules.json` is causing a `429` response when `infinite_scroll.js` sends a `POST` request:
```
            {
                "name": "block accept everything",
                "filters": ["!Header:Accept=text/html"],
                "limit": 0,
                "stop": true,
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
```
Removing this rule allows the request to go through.

Unreproducible on:
https://searx.me/
https://searx.be/
https://searx.tuxcloud.net/
, probably because they do not have `filtron`?

**Comment by unixfox** [comment]
I ran into the same issue when developing [antibot-proxy](https://github.com/unixfox/antibot-proxy) for https://searx.be.
Furthermore, I had to add some code especially to workaround this bug.

**Comment by dalf** [comment]
The last docker image (```searx/searx:0.15.0-430-54675c76```) fixes the issue.
