### ISSUE TITLE
Port in use

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx-docker#19]
Hello,

I would install searx but get this message 

`morty            | WARNING: no logs are available with the 'none' log driver
caddy            | 2019/12/18 10:01:51 [WARNING] Stapling OCSP: no OCSP stapling for [localhost]: no OCSP server specified in certificate
caddy            | Activating privacy features... done.
caddy            | 2019/12/18 10:01:51 Listen: listen tcp :443: bind: address already in use
caddy            | exit status 1 `

But in Docker-compose.yaml

`version: '3.7'
  
services:

  caddy:
    container_name: caddy
    image: abiosoft/caddy:1.0.3-no-stats
    ports:
- 8888:80
- 4449:443
    network_mode: host
    command: -email ${LETSENCRYPT_EMAIL} -agree=${LETSENCRYPT_AGREE} -log stdout -host ${SEARX_HOSTNAME} -conf /etc/Caddyfile
    volumes:
- ./Caddyfile:/etc/Caddyfile:rw
- ./caddy:/root/.caddy:rw
- ./srv:/srv:rw
- searx-checker:/srv/searx-checker:rw
    environment:
- SEARX_HOSTNAME=${SEARX_HOSTNAME}
- SEARX_PROTOCOL=${SEARX_PROTOCOL:-}
- SEARX_TLS=${SEARX_TLS:-}
- FILTRON_USER=${FILTRON_USER}
- FILTRON_PASSWORD=${FILTRON_PASSWORD}
    cap_drop:
- ALL
    cap_add:
- NET_BIND_SERVICE
- DAC_OVERRIDE
`

**Comment by dalf** [comment]
Sorry for the very long delay to answer.

```bind: address already in use caddy```: there is (was) a server already listening on the port 443.

**Comment by Happyfeet01** [comment]
Sorry forgot to close the “issue” I have solved it and still running fine Searx
