### ISSUE TITLE
change log?

### ISSUE THREAD

**Issue by somedevreally** [searx/searx-docker#21]
where can i get change log to searx-docker, 
the image on hub.docker.com says "Updated an hour ago" by searxrobot
i dont see any commit here, i checked upstream searx/searx last commit 7 days or asciimoo/searx last commit 6 days ago.

does the "searxrobot" just adding tag or any kind of maintenance pull from git on docker hub?

**Comment by dalf** [comment]
The docker image is rebuilt every week to keep the Alpines linux packages up to date (Travis CI cron).

The log of the last build: https://travis-ci.org/searx/searx/builds/638842951
Based on https://github.com/searx/searx

**Comment by somedevreally** [comment]
oh ok thanks, wish that page had rss feed support
