### ISSUE TITLE
429 errors

### ISSUE THREAD

**Issue by unixfox** [searx/searx-docker#24]
Some requests get a 429 error. I don't know why but it doesn't happen on the image `woahbase/alpine-searx` even with the same filtron rules as this repository.

I tried to remove the rules `IP limit, all paths` and `useragent limit, all paths` but that didn't fix the issue.

I can reproduce the same bug with Firefox and Chromium on https://a.searx.space which is known to use searx-docker.

![image](https://user-images.githubusercontent.com/4016501/73435285-3d155e80-4340-11ea-8b97-b3ea3712dbb2.png)
![image](https://user-images.githubusercontent.com/4016501/73435458-97162400-4340-11ea-89c5-210c96c8a319.png)

**Comment by dalf** [comment]
What if 
``` "filters": ["Param:q", "Path=^(/|/search)$"],```
is replaced by
``` "filters": ["Param:q", "Path=^(/search)$"],```
?

An AND operator is applied to filters: https://github.com/asciimoo/filtron/blob/93f8b22bc42fabb57d8a4c0ce7b7de706e6034b6/rule/rule.go#L183-L186

but if for some reason it doesn't work, the "search request" rules would be applied to / without condition.

**Comment by unixfox** [comment]
Sorry I switched back to `woahbase/alpine-searx` with a replica of 4 and it works just fine without any 429 error.
I'll try again with the image `searx/searx` tonight if I have time.

**Comment by dalf** [comment]
Note: for each 429, filtron logs show :
```
2020/02/07 13:59:47 Response error: the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection HTTP/1.1 200 OK
Date: Fri, 07 Feb 2020 13:59:47 GMT
Content-Length: 0
```

**Comment by dalf** [comment]
Add
```
add-header = Connection: close
```
at the end of searx/uwsgi.ini to fix the bug (should be a PR in searx).

**Comment by dalf** [comment]
No more issue on a.searx.space : I close the issue.
Feel free to reopen.
