### ISSUE TITLE
Cert is outdated

### ISSUE THREAD

**Issue by Happyfeet01** [searx/searx-docker#28]
Hello,

the certificate is revoked. But i have an valid Cert on the Host-System. How can i import this? 
Caddy log tells me too many request to letsencrypt.

**Comment by dalf** [comment]
> The certificate is revoked. 

How did you get it ?

>  i have an valid Cert on the Host-System

Same question. Is it from Let's encrypt ?

>  How can i import this ?

If you have your own certificate (not from LetsEncrypt). 
See https://caddyserver.com/v1/docs/tls

Put the cert and key files in ./caddy in the host.

In the [.env](https://github.com/searx/searx-docker/blob/master/.env) file, change:
``` sh
# comment both if SEARX_HOSTNAME is NOT localhost
# SEARX_PROTOCOL=https://
SEARX_TLS=/root/.caddy/cert.pem /root/.caddy/key.pem
```

**Comment by Happyfeet01** [comment]
Yes its from letsencrypt. 

Thanks for your help.

**Comment by unixfox** [comment]
It's not recommended importing a letsencrypt certificate because the duration of the certificate is quite short.
