### ISSUE TITLE
Base url still set to localhost

### ISSUE THREAD

**Issue by zoeydawn** [searx/searx-docker#29]
On searx.ninja, a URL value is still set to `localhost`, but I can't find where that value is coming from. 
For example, you can see it here in the head of the html:
`<link rel="alternate" type="application/rss+xml" title="Searx search: searx docker" href="https://localhost/?q=searx%20docker&amp;categories=general&amp;language=en-US&amp;format=rss">`

The image proxy is also broken as the URLs are pointing to `localhost` instead of `searx.ninja`.

However, the `.env` and settings files are updated:
From .env:
![Screenshot from 2020-03-24 17-30-14](https://user-images.githubusercontent.com/5925306/77486901-e8053e80-6dfe-11ea-83fc-027a2f6f86fd.png)

From settings:
![Screenshot from 2020-03-24 17-31-56](https://user-images.githubusercontent.com/5925306/77486932-010def80-6dff-11ea-942b-5cc1e0184b35.png)
![Screenshot from 2020-03-24 17-32-26](https://user-images.githubusercontent.com/5925306/77486939-066b3a00-6dff-11ea-8ea8-6de6b4fdcc13.png)

I cannot figure out where the localhost value is coming from, and the site is not fully functional until I can fix it.

**Comment by zoeydawn** [comment]
I'm closing this issue because I was able to solve the problem

**Comment by FarisZR** [comment]
how?, more details please?
