### ISSUE TITLE
Malformed opensearch.xml in Firefox

### ISSUE THREAD

**Issue by MrHappy** [searx/searx-docker#41]
When I access https://searx.mydomain.org/opensearch.xml in Firefox I get
`searx a privacy-respecting, hackable metasearch engine UTF-8 /static/themes/oscar/img/favicon.png searx metasearch`
When I open the same url in Edge I get
`<?xml version="1.0" encoding="ISO-8859-1"?>`
`<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">`
`<ShortName>searx</ShortName>`
`<Description>a privacy-respecting, hackable metasearch engine</Description>`
`<InputEncoding>UTF-8</InputEncoding>`
`<Image>/static/themes/oscar/img/favicon.png</Image>`
`<LongName>searx metasearch</LongName>`
`<Url template="/search?q={searchTerms}" method="get" type="text/html"/>`
`</OpenSearchDescription> `
It makes no difference if use Nginx in front of uwsgi or not.
In nginx.conf I've tried it with gzip on and the setting disabled.
Anybody got a clue??

**Comment by unixfox** [comment]
Are you sure it's a bug in the dockerized version of searx and not searx itself?

Did you try on a Searx local installation without docker?

**Comment by MrHappy** [comment]
Somewhere it was fixed.
