### ISSUE TITLE
Update dalf/morty docker image

### ISSUE THREAD

**Issue by joshu9h** [searx/searx-docker#42]
Hello is it possible to update the dalf/morty to the latest morty master
In the latest morty it is possible to switch to socks5

thx

**Comment by dalf** [comment]
Done: 
* https://github.com/dalf/morty/commit/939ebe28caa73249c5ab1172fa44366138224241
* https://hub.docker.com/layers/dalf/morty/latest/images/sha256-72154f1cb356d8959dd61f6a0a504235b60977882b23a243c08ef68e74ff8fe6?context=repo
