### ISSUE TITLE
Installation issues with new version of searx-docker

### ISSUE THREAD

**Issue by ghost** [searx/searx-docker#45]
Title is self-explanatory, not the first time I've reinstalled searx-docker from scratch. 
Never had any issues until now, here are the logs that I got with ./start.sh (note that I replaced my instance link because it is semi-private):

Tested on both Ubuntu 18.04 and 20.04 with identical configuration settings, both give me the same errors.
My hostname isn't localhost, and I've commented and filled out all the necessary parts in the env file.

root@searx:/usr/local/searx-docker# ./start.sh
use docker-compose.yaml
Removing searx-checker ... done
Removing filtron       ... done
Removing caddy         ... done
Removing searx         ... done
Removing morty         ... done
Removing network searx-docker_searx
Removing volume searx-docker_searx-checker
No stopped containers
Creating network "searx-docker_searx" with the default driver
Creating volume "searx-docker_searx-checker" with default driver
Creating filtron       ... done
Creating morty         ... done
Creating searx         ... done
Creating searx-checker ... done
Creating caddy         ... done
Attaching to caddy, searx-checker, morty, searx, filtron
filtron          | 2020/07/13 05:21:00 14 rules loaded from /etc/filtron/rules.json
filtron          | 2020/07/13 05:21:00 Proxy listens on 0.0.0.0:4040
filtron          | 2020/07/13 05:21:00 API listens on 0.0.0.0:4041
morty            | WARNING: no logs are available with the 'none' log driver
caddy            | 2020/07/13 05:20:56 [INFO][cache:0xc000178370] Started certificate maintenance routine
caddy            | Activating privacy features... done.
caddy            |
caddy            | Serving HTTPS on port 443
caddy            | https://domain.com
caddy            |
caddy            | 2020/07/13 05:20:56 [INFO] Serving https://domain.com
caddy            |
caddy            | Serving HTTP on port 80
caddy            | http://domain.com
caddy            |
caddy            | 2020/07/13 05:20:56 [INFO] Serving http://domain.com
searx            | searx version 0.17.0-5-7b19e6c5
searx            |
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 0.0.0.0:8080
searx            | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searx-checker    | Sleep 75 seconds
caddy            | 13/Jul/2020:05:21:51 +0000 [ERROR 502 /] dial tcp 64.90.49.129:4040: i/o timeout
searx-checker    | 2020/07/13 05:22:12 Check with the parameters : -o html/data/status.json http://searx:8080
caddy            | 2020/07/13 05:22:18 http: TLS handshake error from [redacted]:56072: EOF

**Comment by dalf** [comment]
I've updated the configuration to use Caddy v2.

Can you pull the changes, and try again ?

**Comment by ghost** [comment]
Tried again, works flawlessly now. Thanks!
