### ISSUE TITLE
systemd service doesn't start at boot

### ISSUE THREAD

**Issue by hakova** [searx/searx-docker#47]
Hi,

Thanks for this great tool! I have a working set up after following the instructions. My working directory is /home/user/Docker/searx-docker and when I enable the searx-docker.service `(sudo systemctl enable searx-docker.service)` it creates a symlink in /etc/systemd/system/multi-user-target directory pointing to the /home/user/Docker/searx-docker/searx-docker.service file. I can start this service by issuing the `sudo systemctl start searx-docker.service`; however it will not start after reboot. This behavior is consistent, but I don't think it is supposed to be this way. What am I missing?

Thanks!

**Comment by unixfox** [comment]
Is docker starting by itself after a reboot?

**Comment by hakova** [comment]
Yes it is. I have other containers (php-apache, postgresql) that are set to restart always by their docker-compose files, and they restart after reboot, indicating that the docker service is restarting as well.

**Comment by hakova** [comment]
As a follow up to this problem, I realized that although the link to the file exists in /etc/systemd/system/multi-user-target directory to the searx-docker.service file that is located in the user's directory stated above, one needs to re-enable the service after each boot before starting the service fresh. Perhaps the access to the user's home director(ies) are not established when the service is attempted to start by systemctl? Just a guess...

**Comment by hakova** [comment]
I copied the service/unit file to /usr/lib/systemd/system and created a symlink in /usr/lib/systemd/system/multi-user.target.wants, owner being root of course. After that, enabling the service
`#systemctl enable searx-docker.service` used the former file above to create another link in /etc/systemd/system/multi-user.target.wants directory. This way, the service is starting at boot without problem. Perhaps you should consider this method over the one below recommended in the wiki:
`systemctl enable $(pwd)/searx-docker.service`
