### ISSUE TITLE
adding searx to firefox preview/nightly on Android is impossible due to block by filtron

### ISSUE THREAD

**Issue by unixfox** [searx/searx-docker#48]
On Firefox preview/nightly for Android it's impossible to add a Searx instance behind searx-docker due to filtron which is blocking the request when adding the instance as a search engine.

![Screenshot_20200725-143048_Firefox_Nightly_1_1](https://user-images.githubusercontent.com/4016501/88457098-fa15ed00-ce83-11ea-983c-f61be9d5df72.png)

It sends these headers when trying to add Searx as a search engine:
````
User-Agent: MozacFetch/50.0.20200712190143
Accept: */*
Accept-Language: */*
Accept-Encoding: gzip
Connection: keep-alive
````

Its request is blocked by these two rules:
- [block no deflate support](https://github.com/searx/searx-docker/blob/master/rules.json#L84)
- [block accept everything](https://github.com/searx/searx-docker/blob/master/rules.json#L94)

How to resolve the issue?

Should we whitelist only the specific user agent `MozacFetch` in order to solve the issue?
Or should we just whitelist the keyword `1` (`?q=1`) which is hardcoded into the fenix source code: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/settings/search/SearchStringValidator.kt#L18?

Related issue: https://github.com/mozilla-mobile/fenix/issues/11332

**Comment by dalf** [comment]
Where to download this version? 

I have this one:
![Screenshot_20200725-150644_Firefox Nightly](https://user-images.githubusercontent.com/1594191/88457669-980bb680-ce88-11ea-9bf8-297643f4f814.jpg)

But the user agent is ```Mozilla/5.0 (Android 8.0.0; Mobile; rv:80.0) Gecko/80.0 Firefox/80.0```. 

[EDIT] Sorry for the big screenshot.

**Comment by unixfox** [comment]
Just use whatever version of new Firefox on Android that you want. The bug is present on all of them (except Firefox stable on Android) including the one that you sent (Firefox nightly).

**Comment by dalf** [comment]
> Should we whitelist only the specific user agent MozacFetch in order to solve the issue?

An unique filter about the user agent would give an easy access to the bots.

> Or should we just whitelist the keyword 1 (?q=1) which is hardcoded into the fenix source code

Why not combine the keyword and the user agent ?

It works with this rule after the ```bot forbidden``` rule:
```
            {
                "name": "Firefox android",
                "filters": ["Param:q=1", "Header:User-Agent=MozacFetch/", "Header:Accept=\\*/\\*", "Header:Accept-Language=\\*/\\*"],
                "stop": true,
                "actions": [{"name": "log"}]
            },
```

* I've initially added the filter```"Header:Te=trailers"```, and then removed it: 
  *  ```1``` still makes a query to bing, google, etc. but not very useful for the bots.
  * we know this browser sends this header with HTTP/2 but a middlebox may change that...
---
* Firefox Android Beta: ok
* Firefox Android Nightly: I can add searx, but it crashes when I select it later on.

**Comment by unixfox** [comment]
> Why not combine the keyword and the user agent ?

That's a very good idea although I wouldn't add too much filters like Accept and Accept-Language because those could change in the near future. Here is someone seeking for changing the Accept-Language header:  https://github.com/mozilla-mobile/fenix/issues/10605#issuecomment-628025343

I think it's already a very good filter with the combination of q=1 and the user agent mozfetch.

> * I've initially added the filter```"Header:Te=trailers"```, and then removed it: 

Just don't do that, an HTTP request is not always in HTTP2 even if the browser support it, there could be some cases where the client fallback to HTTP1.

> * Firefox Android Nightly: I can add searx, but it crashes when I select it later on.

Does it make an additional request when selecting the searx search engine?

**Comment by dalf** [comment]
> Does it make an additional request when selecting the searx search engine?

no additional request, so it is related to Fenix not Searx. It seems related to https://github.com/mozilla-mobile/fenix/issues/12929 (same stack trace)
