### ISSUE TITLE
How can I use searx internally with docker installation ?

### ISSUE THREAD

**Issue by actionhenkt** [searx/searx-docker#54]
Hi, 
How do I allow my local address to access searx ? It is currently public, but I would like to use it myself too, at the moment I cant connect to it from my lan devices (mobile phone works using 4g connection). Thanks!

**Comment by immanuelfodor** [comment]
I think you need to adjust your router settings. For me there is a port reflection setting that needs to be enabled to access internal services with port forwards on the external IP from within the LAN. I hope it puts you in direction to solve this.
