### ISSUE TITLE
how to renew Letsencrypt certificate

### ISSUE THREAD

**Issue by hakova** [searx/searx-docker#55]
I am sure the answer to this silly question would be very straight forward. Would you please help me in renewing my Letsencrypt certificate, which I believe was obtained by Caddy?

Thanks!

**Comment by unixfox** [comment]
Caddy automatically renew it by itself, no interaction is needed from you.

**Comment by unixfox** [comment]
@hakova any more question about that?

**Comment by hakova** [comment]
Thank you @unixfox for your comment.  I have forwarded unconventional ports from my router to my home server, not 80 or 443, and I believe this messed up Caddy's automatic renewal. This is what I did to get this work, and I am posting below the solution for someone who may have a similar configuration, for future reference:

- I edited the Caddyfile for http and https ports to match 80 and 443 respectively
- I stopped the searx-docker.service
- I forwarded these ports from the router to the server
- I restarted the searx-docker.service, which succeeded in renewing the certificates but failed in starting filtron
- I stopped the searx-docker.service again, re-edited the Caddyfile to its original state to point to the unconventional http and https ports
- I restarted the searx-docker service
- I cancelled forwarding ports 80 and 443 from the router to the server
- I started enjoying my searx server again with my renewed certificate :1st_place_medal:
