### ISSUE TITLE
Error in the Morty container

### ISSUE THREAD

**Issue by ArtMason** [searx/searx-docker#59]
Hello

I am getting an error in the monty container that is as follows.

morty exited with code 1
morty            | WARNING: no logs are available with the 'none' log driver

I am running a linode under Debian 10. I have a bitwarden docker container running fine also. I d see in the docker-compose.yaml file the following is set.

Logging:
Driver: NONE

Any ideas?

Thank you!

**Comment by dalf** [comment]
Can you remove this two lines https://github.com/searx/searx-docker/blob/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/docker-compose.yaml#L73-L74 
and see what kind of error do you have once you have restarted the morty container ?

**Comment by ArtMason** [comment]
Now I get the following

2020/11/02 15:05:28 Error parsing -keyillegal base64 data at input byte 19
morty exited with code 1

**Comment by dalf** [comment]
How do you set MORTY_KEY environment variable ?

As I remember, the key must be set using the environment variable, not using the command line (there is a bug on the command line parsing).

**Comment by ArtMason** [comment]
It appears to be set in yaml file
Environment:
- MORTY KEY=${MORTY_KEY}
- MORTY ADDRESS=0.0.0.0:3000

**Comment by dalf** [comment]
It seems there is an error character #19 of your MORTY_KEY, is it special character ?
Is the key set without without simple quotes ? (so you don't have to escape special characters).

( ```openssl rand -base64 33``` should produce a valid key ).

**Comment by ArtMason** [comment]
There is another container (Bitwarden) listening on port 443. There are no quotes or other characters set with the MORTY_KEY. Should I assume a conflict here? Bitwarden runs an nginx container.

**Comment by dalf** [comment]
I don't think there is a conflict between Bitwarden and Morty.

You should have something like this:
````MORTY_KEY='Ah6+2DTeMlaq/8rV/omkaYlyiJIY3QxCS1/hIKFmEOqs'````

note the ```'``` before and after the key.

**Comment by ArtMason** [comment]
It is only showing MORTY_KEY=${MORTY_KEY]

no associated number anywhere I can find.

**Comment by ArtMason** [comment]
Here is the entire output
artmason@li1962-206:/usr/local/searx-docker$ sudo ./start.sh
use docker-compose.yaml
Removing searx         ... done
Removing morty         ... done
Removing searx-checker ... done
Removing filtron       ... done
Removing caddy         ... done
Removing network searx-docker_searx
No stopped containers
Creating network "searx-docker_searx" with the default driver
Creating searx         ... done
Creating filtron       ... done
Creating morty         ... done
Creating searx-checker ... done
Creating caddy         ... done
Attaching to caddy, searx, searx-checker, morty, filtron
caddy            | {"level":"info","ts":1604334836.121853,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy            | {"level":"warn","ts":1604334836.128459,"logger":"admin","msg":"admin endpoint disabled"}
caddy            | {"level":"info","ts":1604334836.1286645,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
caddy            | {"level":"info","ts":1604334836.128683,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
caddy            | run: loading initial config: loading new config: http app module: start: tcp: listening on :443: listen tcp :443: bind: address already in use
morty            | WARNING: no logs are available with the 'none' log driver
caddy exited with code 1
searx            | searx version 
searx            | 
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 0.0.0.0:8080
searx            | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searx            | [uwsgi-static] added mapping for /static => /usr/local/searx/searx/static
searx-checker    | Sleep 62 seconds
filtron          | 2020/11/02 16:33:57 15 rules loaded from /etc/filtron/rules.json
filtron          | 2020/11/02 16:33:57 API listens on 0.0.0.0:4041
filtron          | 2020/11/02 16:33:57 Proxy listens on 0.0.0.0:4040
morty exited with code 1
morty            | WARNING: no logs are available with the 'none' log driver
morty exited with code 1
morty            | WARNING: no logs are available with the 'none' log driver
morty exited with code 1
morty            | WARNING: no logs are available with the 'none' log driver
morty exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping searx-checker ... done
Stopping morty         ... done
Stopping filtron       ... done
Stopping searx         ... done

I did a reinstall

**Comment by ArtMason** [comment]
I found the information to generate a key. Now below is the output.

artmason@li1962-206:/usr/local/searx-docker$ sudo ./start.sh
use docker-compose.yaml
Removing searx-checker ... done
Removing caddy         ... done
Removing morty         ... done
Removing filtron       ... done
Removing searx         ... done
Removing network searx-docker_searx
No stopped containers
Creating network "searx-docker_searx" with the default driver
Creating searx         ... done
Creating morty         ... done
Creating searx-checker ... done
Creating caddy         ... done
Creating filtron       ... done
Attaching to caddy, searx-checker, searx, filtron, morty
caddy            | {"level":"info","ts":1604336491.572335,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy            | {"level":"warn","ts":1604336491.574856,"logger":"admin","msg":"admin endpoint disabled"}
caddy            | {"level":"info","ts":1604336491.5750437,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
caddy            | {"level":"info","ts":1604336491.575061,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
caddy            | run: loading initial config: loading new config: http app module: start: tcp: listening on :443: listen tcp :443: bind: address already in use
filtron          | 2020/11/02 17:01:32 15 rules loaded from /etc/filtron/rules.json
filtron          | 2020/11/02 17:01:32 API listens on 0.0.0.0:4041
filtron          | 2020/11/02 17:01:32 Proxy listens on 0.0.0.0:4040
morty            | WARNING: no logs are available with the 'none' log driver
caddy exited with code 1
searx            | searx version 
searx            | 
searx            | Use existing /etc/searx/uwsgi.ini
searx            | Use existing /etc/searx/settings.yml
searx            | Listen on 0.0.0.0:8080
searx            | [uWSGI] getting INI configuration from /etc/searx/uwsgi.ini
searx            | [uwsgi-static] added mapping for /static => /usr/local/searx/searx/static
searx-checker    | Sleep 108 seconds
searx-checker    | 2020/11/02 17:03:20 Check with the parameters : -o html/data/status.json http://searx:8080
searx-checker    | Error get  /config , status code= 500
searx-checker    | Sleep 86292 seconds
  

^CGracefully stopping... (press Ctrl+C again to force)
Stopping filtron       ... done
Stopping searx-checker ... done
Stopping morty         ... done
Stopping searx         ... done

If I start searx I do not get any errors, however it still points to my bitwarden install. I am assuming because an ssl certificate has not been issued

**Comment by ArtMason** [comment]
Is this a for a local install? I have searx running great on a server without docker. What I want is to move it and eliminate the server it is running on. I think I will just do a normal install and add it to apache.

Thanks for your time! You can close this.

**Comment by ArtMason** [comment]
Closing issue
