### ISSUE TITLE
Adding searx as search-engine in Firefox mobile

### ISSUE THREAD

**Issue by MrHappy** [searx/searx-docker#60]
When i try to add a searx search engine and put the search string "https://searx.be/?q=%s", it says "Error connecting to searx".
This was resolved some time ago, and now it resurfaced,,,
Similar issue as [https://github.com/searx/searx-docker/issues/48](url)

**Comment by unixfox** [comment]
The user agent used when adding Searx has changed and his now `Mozilla/5.0 (Android 9; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0`.
We need to whitelist this user agent in the rules.

Here are the headers sent by Firefox android when adding Searx as a search engine:
```
User-Agent: Mozilla/5.0 (Android 9; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Te: trailers
```

**Comment by unixfox** [comment]
@MrHappy a PR has been opened https://github.com/searx/searx-docker/pull/61 but the fix is already included on searx.be so you may try again and give me your results.

**Comment by MrHappy** [comment]
@unixfox Thanks! Works fine!
