### ISSUE TITLE
New container overwrites settings.yml (at least partly)

### ISSUE THREAD

**Issue by ih8ms** [searx/searx-docker#62]
## Observed behaviour

Whenever I deploy a new searx container, `settings.yml` will be overwritten, at least partly. In ui, I set `oscar_style` in `theme_args` to 'logicodev-dark', but it will always be reverted to 'logicodev' whenevere I pull a new version of searx/searx.

## Expected behaviour
Running a later version of the searx/searx container shouldn't revert settings to default, especially not theme/visual settings.

I suppose this behaviour is in all 0.17 version images.

**Comment by dalf** [comment]
See:
https://github.com/searx/searx-docker/blob/a7443cdc5f246fe85a63e9b9594bbb4f82e3b6e5/.env#L9-L11

Comment out the line 11, restart: the new version of settings.yml will be copied into `settings.yml.new`

See also https://searx.github.io/searx/admin/installation-docker.html#command-line

**Comment by dalf** [comment]
I close the issue, feel free to comment / reopen.
