### ISSUE TITLE
keep losing my settings.yml

### ISSUE THREAD

**Issue by somedevreally** [searx/searx-docker#7]
Hello,

searx-docker works awesome, but watchtower updates it, and each time it updates my settings.yml get over written.
when i restore my settings.yml and restarting/build the container  still doesn't work.

also on command update.sh, i get this error
fatal: --[no-]autostash option is only valid with --rebase.

am sure am doing something dumb, but cant figure it yet.

thanks

**Comment by dalf** [comment]
The settings.yml is only replace if it has been updated in the docker image, but I agree it is not convenient. You can disable this behavior. In ```.env```, comment the line ```SEARX_COMMAND=-f```, so : 
* searx docker image won't modify your settings.yml
* if there is a new configuration, it will be in settings.yml.new, up to you to update your settings.yml

The real fix would be a separate file searx.override.yaml

update.sh requires more testing.
If you have watchtower, update.sh will update the filtron rules and Caddy configuration.

**Comment by somedevreally** [comment]
ok i commented the line in `.env` and replaced settings.yml everything looks good. will confirm after next update.
the override approach will it be implemented in future? as i tried with the new file and it didn't worked.

thanks and searx is great

**Comment by somedevreally** [comment]
FYI
searx got updated and again lost setting, even after commenting out the line in `.env`

**Comment by dalf** [comment]
Okay :(
 
May I ask you if you have these files : 
* searx/settings.yml.new
* searx/settings.yml.old 
?

**Comment by somedevreally** [comment]
i have 
searx/settings.yml 
searx/settings.yml.old

**Comment by dalf** [comment]
The PR https://github.com/asciimoo/searx/pull/1668 should have fixed the issue (there is a version in hub.docker.com: 0.15.0-144-91a59ff3 )

This old PR might be interesting later: https://github.com/asciimoo/searx/pull/1278 but it requires some update.

**Comment by somedevreally** [comment]
awesome!!! 
docker was auto updated by watchtower 1 hr ago. still have all the settings. cool

so do we need  searx-checker? 

thanks

**Comment by dalf** [comment]
> so do we need searx-checker?

Every 24h, searx-checker checks if your engines are working as expected.
The result is at https://yoursearxurl/status

For the master branch, the result is here: https://searx.space/ (might be different for you because your IP is different).

The purpose is:
* to have list https://stats.searx.xyz/ where you can select the engines you would like to use. In this case the website displays only instances known to have working engines.
* same about website like https://searx.neocities.org/ : pick searx instances that are working.
* to know when an engine needs to be updated: for example searx.space, since some engines behaves differently according to the IP.

In the future, searx-checker will be embedded in the searx docker image.

**Comment by dalf** [comment]
I think the issue resolved.

Additional note: look at searx/settings.yml.new file from time to time to see the updates.

**Comment by somedevreally** [comment]
> The result is at https://yoursearxurl/status

if i go to http://myip/status is says 
```
Page not found
Go to search page.
```

**Comment by dalf** [comment]
Do you have 
```yaml
  rewrite / {
        regexp ^/status$
        to /searx-checker/status.json
  }
```
in your Caddyfile ?

See https://github.com/searx/searx-docker/blob/master/Caddyfile#L60

If not, you should ```git pull``` from the searx-docker project.

**Comment by somedevreally** [comment]
the rewrite code block is, as is in caddyfile

**Comment by dalf** [comment]
In this case try ```./stop.sh``` to restart everything and take the docker-compose.yml possible modification (the systemd service will restart automatically).

Wait 10 minutes, if there is still nothing at https://..../status can you check these points ?

```docker volume ls```
Do you see searx-docker_searx-checker ?

```docker volume inspect searx-docker_searx-checker```
Do you see the ""Mountpoint" ?

```ls /var/lib/docker/volumes/searx-docker_searx-checker/_data``` (or the Mountpoint shown)
Is there a status.json file ?

```cat /var/lib/docker/volumes/searx-docker_searx-checker/_data/status.json```
What is the content ?

**Comment by somedevreally** [comment]
sorry for delayed response...
`Do you see searx-docker_searx-checker ?`
no i do not see this volume.
