### ISSUE TITLE
E: The page isn’t redirecting properly

### ISSUE THREAD

**Issue by zevlee** [searx/searx-docker#76]
Upon updating to the most recent docker image ``sudo docker pull searx/searx:latest`` (i.e. 1.0.0-26-70895267) there is an issue with accessing the home page of searx instances.

Attempting to visit the home page of the instance https://searx.bar results in an error. In the case of Firefox-based browsers, it's "The page isn't redirecting properly."

However, querying through the URL works just fine as seen here: https://searx.bar/search?q=test

**Comment by zevlee** [comment]
I've temporarily set my searx instance to the stable version until the issue is resolved. https://searx.likkle.monster/ happens to be suffering from the issue described in the parent post.

**Comment by cybermcm** [comment]
same problem here...

**Comment by unixfox** [comment]
Duplicate of #2729

**Comment by cybermcm** [comment]
https://github.com/searx/searx/issues/2729
