### ISSUE TITLE
Error when running start.sh

### ISSUE THREAD

**Issue by ghost** [searx/searx-docker#92]
On a fresh install, when I run the start script, it tells me this:
```
use docker-compose.yaml
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
I've updated to both docker `18.09.1` and docker-compose `1.21.0`. I haven't made any changes to anything besides the `.env` file. I'm running the script as root if that makes any difference.

**Comment by unixfox** [comment]
Last version of docker-compose is 1.29.2: https://github.com/docker/compose/releases/tag/1.29.2 so just install this new version and the issue will be fixed: https://docs.docker.com/compose/install/
